alias ls='ls --color=auto'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF' 
alias lll='ls -alF --color=always |less -XR'
alias grep='grep --color=auto'
alias sudo='sudo '
alias vi='nvim'
alias xopen='xdg-open'
